import pandas as pd
from pathlib import Path
from datetime import datetime


class ModelStatusService:
    """
    ModelStatusService
    ------------------
    Provides transparency into the currently active
    production forecasting model.

    Responsibilities:
    - Load model metadata generated by offline notebooks
    - Expose model performance & configuration
    - Support UI & BI dashboards
    """

    def __init__(self):
        # --------------------------------------------------
        # Resolve project base directory safely
        # --------------------------------------------------
        self.base_dir = Path(__file__).resolve().parents[3]

        # --------------------------------------------------
        # Metadata file produced by model comparison notebook
        # --------------------------------------------------
        self.metadata_path = (
            self.base_dir
            / "models"
            / "production_model_metadata.csv"
        )

    def get_status(self) -> dict:
        """
        Returns metadata for the active production model.

        Output is intentionally simple and JSON-serializable
        for easy UI and Power BI consumption.
        """

        if not self.metadata_path.exists():
            return {
                "status": "metadata_not_found",
                "message": "Production model metadata not available."
            }

        metadata = pd.read_csv(self.metadata_path).iloc[0]

        return {
            "status": "active",
            "active_model": metadata["selected_model"],
            "selection_metric": metadata["selection_metric"],
            "mae": round(float(metadata["mae"]), 2),
            "rmse": round(float(metadata["rmse"]), 2),
            "training_records": int(metadata["train_size"]),
            "features_used": self._parse_features(
                metadata["features_used"]
            ),
            "last_updated": self._last_updated(),
        }

    # --------------------------------------------------
    # Helpers
    # --------------------------------------------------
    def _parse_features(self, features_raw: str):
        """
        Converts feature list stored as string into Python list.
        """
        return (
            features_raw
            .strip("[]")
            .replace("'", "")
            .split(", ")
        )

    def _last_updated(self) -> str:
        """
        Returns last modified time of metadata file.
        """
        ts = self.metadata_path.stat().st_mtime
        return datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")
